# Generated by Django 5.0.14 on 2026-05-12 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referring_doctor_id', models.UUIDField(help_text='User ID of the referring doctor')),
                ('patient_summary', models.JSONField(default=dict, help_text='Anonymized patient clinical summary (not an FK — HIPAA compliant)')),
                ('reason', models.TextField(help_text='Reason for referral')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'Stat')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('clinical_notes', models.TextField(blank=True)),
                ('accepted_by_id', models.UUIDField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('from_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_referrals', to='tenants.organization')),
                ('to_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_referrals', to='tenants.organization')),
            ],
            options={
                'db_table': 'referrals_referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_id', models.UUIDField()),
                ('content', models.TextField()),
                ('author_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='referrals.referral')),
            ],
            options={
                'db_table': 'referrals_note',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('established_at', models.DateTimeField(blank=True, null=True)),
                ('data_sharing_agreement', models.BooleanField(default=False, help_text='Whether a data sharing agreement is in place')),
                ('notes', models.TextField(blank=True)),
                ('from_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_connections', to='tenants.organization')),
                ('to_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_connections', to='tenants.organization')),
            ],
            options={
                'db_table': 'referrals_facility_connection',
                'ordering': ['-created_at'],
                'unique_together': {('from_tenant', 'to_tenant')},
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['from_tenant', 'status'], name='referrals_r_from_te_279f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['to_tenant', 'status'], name='referrals_r_to_tena_9d6d99_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['priority', '-created_at'], name='referrals_r_priorit_418f85_idx'),
        ),
    ]
