# Generated by Django 5.0.14 on 2026-05-21 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenantMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email used for this tenant (may differ from primary)', max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('keycloak_subject_id', models.CharField(blank=True, db_index=True, help_text="Keycloak sub for this user in this tenant's realm", max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user-tenant mapping',
                'verbose_name_plural': 'user-tenant mappings',
                'db_table': 'accounts_user_tenant_mapping',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tenantmembership',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantmembership',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersecrets',
            name='mfa_backup_codes_encrypted',
        ),
        migrations.RemoveField(
            model_name='usersecrets',
            name='refresh_token_encrypted',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional username (auto-generated from email if blank)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersecrets',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersecrets',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usersecrets',
            name='secret',
            field=models.TextField(blank=True, default='', help_text='Application secret (e.g., TOTP seed, recovery codes encrypted)'),
        ),
        migrations.AddField(
            model_name='usersecrets',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Platform admin flag (equivalent to WhiteMatter superadmin).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, db_index=True, help_text='Keycloak subject (sub claim)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='idx_user_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='usersecrets',
            index=models.Index(fields=['user'], name='idx_user_secrets_user_id'),
        ),
        migrations.AddField(
            model_name='usertenantmapping',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='usertenantmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TenantMembership',
        ),
        migrations.AddIndex(
            model_name='usertenantmapping',
            index=models.Index(fields=['email'], name='idx_utm_email'),
        ),
        migrations.AddIndex(
            model_name='usertenantmapping',
            index=models.Index(fields=['keycloak_subject_id'], name='idx_utm_keycloak_subject'),
        ),
        migrations.AddIndex(
            model_name='usertenantmapping',
            index=models.Index(fields=['is_deleted'], name='idx_utm_is_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='usertenantmapping',
            unique_together={('user', 'tenant')},
        ),
    ]
