# Generated by Django 5.0.14 on 2026-05-06 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateTimeField()),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('examination_notes', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='appointments.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'db_table': 'medical_records_visit',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd_code', models.CharField(db_index=True, help_text='ICD-10/11 code', max_length=20)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('rule_out', 'Rule Out')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical_records.visit')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'db_table': 'medical_records_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Celsius', max_digits=4, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='Percentage', max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by_id', models.UUIDField(help_text='References accounts.User.id')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='medical_records.visit')),
            ],
            options={
                'verbose_name_plural': 'vitals',
                'db_table': 'medical_records_vitals',
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'visit_date'], name='medical_rec_patient_107acb_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['doctor', 'visit_date'], name='medical_rec_doctor__ad7c33_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['visit'], name='medical_rec_visit_i_82f4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['icd_code'], name='medical_rec_icd_cod_31187a_idx'),
        ),
    ]
