# Generated by Django 5.0.14 on 2026-06-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0002_add_customer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('pharmacy_order', 'Pharmacy Order'), ('lab_order', 'Lab Order'), ('radiology_order', 'Radiology Order'), ('manual', 'Manual')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient'),
        ),
    ]
