# Generated by Django 5.0.14 on 2026-05-06 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_id', models.UUIDField(db_index=True, help_text='User ID of the requester')),
                ('request_type', models.CharField(choices=[('prescription_ocr', 'Prescription OCR'), ('lab_analysis', 'Lab Analysis'), ('radiology', 'Radiology')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict, help_text='Sanitized input sent to AI service')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='Response from AI service')),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Round-trip latency in ms')),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='patients.patient')),
            ],
            options={
                'db_table': 'ai_integration_ai_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['request_type', 'status'], name='ai_integrat_request_13a051_idx'), models.Index(fields=['requested_by_id', 'requested_at'], name='ai_integrat_request_44d20a_idx')],
            },
        ),
    ]
