# Generated by Django 5.0.14 on 2026-05-06 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler')], max_length=20)),
                ('strength', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prescriptions_medication',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='appointments.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='medical_records.visit')),
            ],
            options={
                'db_table': 'prescriptions_prescription',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(help_text='e.g., "500mg"', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., "twice daily"', max_length=100)),
                ('duration', models.CharField(help_text='e.g., "7 days"', max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('topical', 'Topical'), ('sublingual', 'Sublingual'), ('inhalation', 'Inhalation')], default='oral', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True, help_text='e.g., "after meals"')),
                ('is_prn', models.BooleanField(default=False, help_text='As-needed basis')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescriptions_prescription_item',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'prescribed_at'], name='prescriptio_patient_15365f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'prescribed_at'], name='prescriptio_doctor__59bcb9_idx'),
        ),
    ]
