# Generated by Django 5.0.14 on 2026-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, help_text='What the drug is and what it treats'),
        ),
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medications/'),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='storage_instructions',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
