# Generated by Django 5.0.14 on 2026-05-21 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('resource', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_permissions',
                'ordering': ['resource', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_roles',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='FK to public schema accounts_user.id')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('keycloak_subject_id', models.CharField(blank=True, db_index=True, help_text="Keycloak sub claim for this user in this tenant's realm", max_length=255, null=True)),
                ('specialty', models.CharField(blank=True, default='', help_text='Medical specialty (e.g., Cardiology, Pediatrics, General Practice)', max_length=100)),
                ('license_number', models.CharField(blank=True, default='', help_text='Professional medical license number', max_length=100)),
                ('qualification', models.CharField(blank=True, default='', help_text='Professional qualification (MD, RN, PharmD, etc.)', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('dashboard_configurations', models.JSONField(blank=True, default=list)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_configured_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='rbac.role')),
            ],
            options={
                'db_table': 'rbac_tenant_users',
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_invitations', to='rbac.tenantuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invitations', to='rbac.role')),
            ],
            options={
                'db_table': 'rbac_user_invitations',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role')),
            ],
            options={
                'db_table': 'rbac_role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['status'], name='idx_tenant_users_status'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['role'], name='idx_tenant_users_role'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['email'], name='idx_invitations_email_active'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['status'], name='idx_invitations_status_active'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(condition=models.Q(('is_deleted', False), ('status', 'PENDING')), fields=['expires_at'], name='idx_invitations_pending_expiry'),
        ),
        migrations.AddConstraint(
            model_name='userinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'PENDING')), fields=('email',), name='uq_invitations_pending_email'),
        ),
    ]
