# Generated by Django 5.0.14 on 2026-05-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantuser',
            new_name='idx_users_status',
            old_name='idx_tenant_users_status',
        ),
        migrations.RenameIndex(
            model_name='tenantuser',
            new_name='idx_users_role_id',
            old_name='idx_tenant_users_role',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permissions',
        ),
        migrations.AlterModelTable(
            name='tenantuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userinvitation',
            table='user_invitations',
        ),
    ]
