# Generated by Django 5.0.14 on 2026-05-06 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(db_index=True, help_text='e.g., Patient, Invoice', max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('description', models.TextField(blank=True)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=63)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": {"old": ..., "new": ...}}')),
                ('request_id', models.CharField(blank=True, help_text='Correlation ID', max_length=36)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='audit_log_user_id_835db7_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx'), models.Index(fields=['tenant_schema', 'timestamp'], name='audit_log_tenant__6c18b1_idx')],
            },
        ),
    ]
