# Generated by Django 5.0.14 on 2026-05-12 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispensed_by_id', models.UUIDField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'pharmacy_dispense_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this level')),
                ('reorder_quantity', models.PositiveIntegerField(default=50, help_text='Suggested reorder quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Shelf/room location', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='prescriptions.medication')),
            ],
            options={
                'db_table': 'pharmacy_inventory',
                'ordering': ['medication__name', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DispenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('dispense_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispenserecord')),
                ('inventory', models.ForeignKey(blank=True, help_text='Inventory batch dispensed from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacyinventory')),
            ],
            options={
                'db_table': 'pharmacy_dispense_item',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('received', 'Received'), ('dispensed', 'Dispensed'), ('adjusted', 'Adjusted'), ('expired', 'Expired'), ('returned', 'Returned')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for removals')),
                ('balance_after', models.PositiveIntegerField(help_text='Stock level after transaction')),
                ('reference', models.CharField(blank=True, help_text='Reference (e.g., PO number, prescription ID)', max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('performed_by_id', models.UUIDField(help_text='User who performed the transaction')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pharmacy.pharmacyinventory')),
            ],
            options={
                'db_table': 'pharmacy_stock_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['medication', 'batch_number'], name='pharmacy_in_medicat_6b3b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['expiry_date'], name='pharmacy_in_expiry__c0dde1_idx'),
        ),
    ]
