# Generated by Django 5.0.14 on 2026-06-11 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_source_customer_fields'),
        ('patients', '0002_add_customer_model'),
        ('pharmacy', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_by_id', models.UUIDField(help_text='Pharmacist user id')),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='patients.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders', to='billing.invoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, help_text='Set when the order originates from a prescription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'pharmacy_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inventory', models.ForeignKey(blank=True, help_text='Inventory batch fulfilled from (set at fulfillment)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacyinventory')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacyorder')),
            ],
            options={
                'db_table': 'pharmacy_order_item',
            },
        ),
    ]
