# Generated by Django 5.0.14 on 2026-06-11 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_add_availability_models'),
        ('billing', '0002_add_source_customer_fields'),
        ('medical_records', '0001_initial'),
        ('patients', '0002_add_customer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('awaiting_report', 'Awaiting Report'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=30)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'Stat')], default='routine', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiology_orders', to='patients.customer')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiology_orders', to='appointments.doctorprofile')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='billing.invoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiology_orders', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='medical_records.visit')),
            ],
            options={
                'db_table': 'radiology_order',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammography', 'Mammography'), ('fluoroscopy', 'Fluoroscopy'), ('pet', 'PET Scan')], max_length=20)),
                ('body_part', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('performed_by_id', models.UUIDField(blank=True, help_text='Radiographer user id', null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='radiology.radiologyorder')),
            ],
            options={
                'db_table': 'radiology_study',
            },
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('findings', models.TextField()),
                ('impression', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Critical/urgent finding flag')),
                ('reported_by_id', models.UUIDField(help_text='Radiologist user id')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('image_object_key', models.CharField(blank=True, help_text='MinIO object key for the image, if uploaded', max_length=500)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='radiology.radiologystudy')),
            ],
            options={
                'db_table': 'radiology_report',
            },
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['status', 'priority'], name='radiology_o_status_cdf75e_idx'),
        ),
    ]
