# Generated by Django 5.0.14 on 2026-05-06 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(db_index=True, help_text='References accounts.User.id in public schema.')),
                ('specialization', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('qualification', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'appointments_doctor_profile',
                'indexes': [models.Index(fields=['user_id'], name='appointment_user_id_4e4231_idx'), models.Index(fields=['specialization'], name='appointment_special_e46ed3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('type', models.CharField(choices=[('in_person', 'In Person'), ('telehealth', 'Telehealth')], default='in_person', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by_id', models.UUIDField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.doctorprofile')),
            ],
            options={
                'db_table': 'appointments_appointment',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['doctor', 'scheduled_at'], name='appointment_doctor__2f3cbe_idx'), models.Index(fields=['patient', 'scheduled_at'], name='appointment_patient_42b596_idx'), models.Index(fields=['status', 'scheduled_at'], name='appointment_status_eec9f6_idx')],
            },
        ),
    ]
