# Generated by Django 5.0.14 on 2026-06-16 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(db_index=True, help_text='User ID from public schema')),
                ('token', models.CharField(max_length=512)),
                ('platform', models.CharField(default='web', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notifications_push_device',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pushdevice',
            constraint=models.UniqueConstraint(fields=('user_id', 'token'), name='uniq_user_device_token'),
        ),
    ]
